### ISSUE TITLE
What does the CUSTOM_LABEL_MAP represent？And How to modify it?

### ISSUE THREAD

**Issue by FinalFlowers** [feiyuhuahuo/Yolact_minimal#11]
I try to train on my own dataset with only one class, but I'm not sure how to modify CUSTOM_LABEL_MAP to adapt to my dataset. Could you help me?

**Comment by feiyuhuahuo** [comment]
Modify it as: `CUSTOM_LABEL_MAP = {1: 1}`

**Comment by FinalFlowers** [comment]
@feiyuhuahuo When I modify it as `CUSTOM_LABEL_MAP = {1: 1}`, an error occured:

**Comment by feiyuhuahuo** [comment]
For this line: `self.label_map[obj['category_id']] - 1`, check your `obj['category_id']`, it should be 1.  CUSTOM_LABEL_MAP does nothing when training custom dataset. It's for code compatibility. Because when reading data from COCO json files, the 80 class labels are from 1 to 90 instead of from 1 to 80 and are not continuous. So  we need another `dict` to deal with it.

**Comment by FinalFlowers** [comment]
I found that the category_id of my dataset is 0, so I changed it to `CUSTOM_LABEL_MAP = {0: 1}` and it worked. Thank you!
